List<String> cargosDincydet = [
  'Director',
  'Subdirector',
  'Maestro de armas',
  'Jefe',
  'SubJefe',
  'Tecnico',
  'Otro'
];

List<String> areasDincydet = [
  'Direccion',
  'SubDireccion',
  'Departamento de Proyectos de Ingenieria',
  'Departamento de Control de Proyectos',
  'Departamento de Proyectos de Electronica',
  'Departamento de Sistemas operacionales',
  'Secretaria y Comunicaciones',
  'Estación Telemática',
  'Administracion',
  'Oficina de personal',
  'Otro',
];

List<String> bloodTypes = [
  'O+',
  'O-',
  'AB+',
  'AB-',
  'A+',
  'A-',
  'B+',
  'B-',
];

List<String> alertTypes = [
  'Incendio',
  'Combate',
  'Sismo y Tsunami',
  'Evacuacion de Emergencia',
];

List<String> gradeTypes = [
  'VALM - VICEALMIRANTE',
  'CALM - CONTRALMIRANTE',
  'C. DE N. - CAPITAN DE NAVIO',
  'C. DE F. - CAPITAN DE FRAGATA',
  'C. DE C. - CAPITAN DE CORBETA',
  'TEPRI - TENIENTE PRIMERO',
  'TESE - TENIENTE SEGUNDO',
  'AFRA - ALFEREZ DE FRAGATA', // 7 Persuba de aqui hacia abajo
  'TS1 - TECNICO SUPERVISOR PRIMERO',
  'TS2 - TECNICO SUPERVISOR SEGUNDO',
  'T1 - TECNICO PRIMERO',
  'T2 - TECNICO SEGUNDO',
  'T3 - TECNICO TERCERO',
  'OM1 - OFICIAL DE MAR PRIMERO',
  'OM2 - OFICIAL DE MAR SEGUNDO',
  'OM3 - OFICIAL DE MAR TERCERO', // 16 Persuba hasyta aqui
  'CB1 - CABO PRIMERO', // Permar
  'CB2 - CABO SEGUNDO',
  'MAR - MARINERO',
  'GRU - GRUMETE', // Hasta aqui Permar
  'PERCIVI - PERSONAL CIVIL',
];

// Constants for document management
List<String> documentManagementTypes = [
  'Mensaje Naval',
  'Oficio',
  'Memorándum',
  'Guia de destino',
  'Otro',
];

// Constant for documents
List<String> documentTypes = [
  'Vacaciones',
  'Permiso',
  'Comisión',
  'Cambio de guardia',
  'Audiencia',
];

// Constants for actions on document assignation
const List<String> actionTypes = [
  'Aprobado',
  'Su Acción',
  'Su Estudio',
  'Su Opinión',
  'Su Recomendación',
  'Su Consideración',
  'Su Coordinación',
  'Su Conocimiento',
  'Su Evaluación',
  'Su Explotación',
  'Su Tramitación',
  'Su Seguimiento',
  'Su Devolución',
  'Preparar Respuesta',
  'Preparar Directiva',
  'Archivo',
  'Otros',
];

// Constants for user
const List<String> userLaboralConditions = [
  'DOTACIÓN',
  'DESTACADO DEL',
  'DESTACADO AL',
  'FORÁNEO',
];

const List<String> userTemporalConditions = [
  'Ninguna',
  'Hospitalizado',
  'Descanso Médico',
  'Exonerado de formación',
];

// Constants for inventory conditions
const List<String> inventoryConditions = [
  'Activo Habido',
  'Reasignado',
  'Baja',
];

// Constants for personal
const List<String> personalTypes = [
  'Presentes',
  'Permiso',
  'Vacaciones',
  'Comisión',
  'Guardia',
  'Destacado al',
  'Hospitalizado',
  'Descanso Médico',
  'Exonerado',
  'Falto',
];

// Constants for inventory types
const List<String> inventoryTypes = [
  '5821 Equipos de comunicaciones (transmisores y receptores)',
  '5975 Montajes y racks',
  '6110 Estabilizadores y reguladores de voltaje para equipos de comunicaciones',
  '5985 Líneas de transmisón de antenas',
  '5985 Antenas, torres de abordo y tierra',
  '5820 Sistema de monitoreo',
  '5820 Sistema de transmisión y recepción de datos',
  '5815 Sistema de telex, telegrafía y cables',
  '5815 Sistema facsímil',
  '5820 Sistema satelital y estaciones terrenas',
  '6130 Sistema de protección eléctrica',
  '5830 Sistema de intercomunicaciones y publidifusión',
  '5831 Sistema de intercomunicaciones y publidifusión',
  '5811 Cifradores de texto',
  '5811 Cifradores de voz',
  '5811 Cifradores de fax',
  '6940 Simuladores para entrenamiento de equipos de comunicaciones',
  '6940 Simuladores para entrenamiento de guerra electrónica de comunicaciones',
  '6940 Otros equipos de enseñanza de su competencia',
  '6940 Simuladores de juego de operaciones tácticas navales, (excepto en toma de decisiones de armas a emplearse)',
  '5820 Equipos de comunicaciones',
  '5820 Equipos de sistema data link',
  '5820 Equipos de presentación',
  '5820 Equipos automáticos de archivos',
  '5820 Equipos de procesamiento',
  '5820 Equipos de comunicaciones interiores',
  '5820 Equipos de software operacional',
  '5820 Equipos de redes de área local y área extendida',
  '5820 Equipos de información',
  '5820 Equipos de sistemas de comunicaciones orientados a comando y control',
  '5820 Equipos de integración de otros sistemas',
  '5805 Centrales telefónicas',
  '5805 Equipos de plantas externas',
  '5805 Equipos de interconexión de centrales',
  '5820 Equipo de equipamento de radio Enlace',
  '5820 Radio teléfono',
  '5820 Movilófonos',
  '6350 Equipos de sistema de seguridad periférica',
  '5865 Equipos para búsqueda y vigilancia',
  '5865 Equipos de monitoreo de comunicaciones',
  '5865 Equipos de análisis de comunicaciones',
  '5865 Equipos de control de comunicaciones',
  '5865 Equipos de interferencia de comunicaciones',
  '6625 Equipos electrónicos, instrumentos, herramientas y laboratorios instalados abordo, en tierra y dedicados principalmente a trabajos de reparación...',
  '5110 Herramientas de mano cortantes',
  '5120 Herramientas de mano no cortantes',
  '5130 Herramientas a mano con motor',
  '5805 Telégrafos de ordenes',
  '5805 Telégrafos en general',
  '6110 Tablero de luces',
  '6145 Cable eléctrico',
  '6320 Alarmas',
  '5830 Anunciadores',
  '8465 Megáfonos',
  '5805 Intercomunicadores',
  '7010 Equipo de computadoras',
  '7010 Equipos de microcomputadoras',
  '7021 Equipos procesadoras',
  '7025 Impresoras',
  '7025 Terminales',
  '7025 Unidades de Disco',
  '7025 Equipos de unidades de interconexion',
  '7000 Equipos de prueba, verificación de cintas magnéticas',
  '7000 Reacondicionadores de tarjetas',
  '7000 Equipos rebobinadores',
  '7000 Otros equipos',
  '7025 Lector de DNI Electrónico',
  '7000 Tarjetas',
  '7000 Cintas magnéticas',
  '7000 Discos removibles, diskettes y CD',
  '7000 Papel para impresoras, tabuladoras y otros',
  '7000 Otros repuestos y materiales',
  '7510 Rollos papel TTY',
  '7510 Rollos para fax',
  '7510 Cintas de punchar para telex',
  '7510 Cintas entintadas (DIN) para TTY',
  '7510 Cintas casette para TTY electrónicos',
  '7510 Cintas para equipos de criptografía',
  '7510 Rollos papel térmico para equipos facsímil',
  '5900 Repuestos para equipos de comunicaciones',
  '5900 Material para laboratorio de electrónica',
  '5900 Material fotográfico y fonotécnico (criptográfica)',
  '5900 Material para recorrido de torres y antenas',
  '5900 Material para instalación y acondicionamiento de equipos de comunicaciones',
  '6625 Herramientas para laboratorios de electrónica y talleres de reparación de equipos de comunicaciones, cada repuesto y/o material por su naturaleza...',
  '6010 Conductores de fibra óptica',
  '6015 Cables de fibra óptica',
  '6020 Arneses y asemblajes para cables de fibra óptica',
  '6030 Dispositivos de fibra óptica',
  '6060 Interconectores de fibra óptica',
  '6070 Material consumible y accesorios de fibra óptica',
  '6080 Juegos y conjunto de fibra óptica',
  '5905 Resistencias',
  '5910 Capacitores',
  '5915 Filtros',
  '5920 Fusibles',
  '5925 Interruptores',
  '5930 Automáticos(disyuntivas)',
  '5935 Interruptores eléctricos',
  '5940 Conectores eléctricos',
  '5940 Terminales',
  '5945 Relays',
  '5950 Imanes',
  '5950 Bobina y transformadores',
  '5955 Cristales',
  '5960 Válvulas electrónicas',
  '5961 Semiconductores',
  '5962 Circuitos integrados',
  '5963 Módulos electrónicos',
  '5965 Auriculares',
  '5965 Microteléfonos',
  '5965 Audífonos',
  '5965 Parlantes',
  '5970 Aisladores y material aislante',
  '5975 Cajas para conductores',
  '5975 Cajas bastidores',
  '5975 Cajas para rack',
  '5975 Ferretería asociada',
  '5980 Ferreteía asociada y dispositivos optoelectrónicos',
  '5985 Antenas, guías de onda y equipos relacionados',
  '5990 Sincros',
  '5995 Sistemas de cables flexibles y alambres para equipos de comunicaciones',
  '5998 Tarjetas electrónicos',
];

// Dependencias
const List<String> dependencies = [
  "MINDEF",
  "COMGEMAR",
  "AGREDEF-ALEMANIA",
  "AGREDEFNAV-ARGENTINA-URUG",
  "SECOGRAL",
  "AGREDEFNAV-BOLIV-PARAG",
  "AGREDEFNAV-BRASIL",
  "AGREDEFNAV-COLOMBIA",
  "AGREDEFNAV-CHILE",
  "IPECAMAR",
  "AGREDEFNAV-ECUADOR",
  "AGREDEFNAV-EE.UU.",
  "AGREDEFNAV-FRANCIA",
  "AGREDEF-GRAN_BRET-IRLANDA",
  "AGREDEF-ITALIA",
  "AGREDEF-PANAMA",
  "AGREDEF-JAPON",
  "JEMGEMAR",
  "COMFAS",
  "FOVIMAR",
  "DIPERMAR",
  "DIRTEL",
  "DIRECOMAR",
  "DIFOSERECE",
  "JEDICAP-1",
  "DICAPI",
  "JEDICAP-3",
  "JEDICAP-4",
  "JEDICAP-5",
  "COMESTARSUB",
  "COMESTAMI",
  "JETADEMU",
  "DIMATEMAR",
  "DIRBIEMAR",
  "JERESEMO",
  "DIRPRONAV",
  "DIRCENTAC",
  "DIRESAN",
  "DINTEMAR",
  "DICEMENA",
  "DIABASTE",
  "DIPERADMON",
  "DICLINAI",
  "JESAE",
  "DIHIDRONAV",
  "COMZOUNO",
  "COMZODOS",
  "COMZOTRES",
  "COMZOCUATRO",
  "COMZOCINCO",
  "COMESMOLE",
  "PROCUMAR",
  "DIRINTEMAR",
  "COMESTRE",
  "DIMAR",
  "DIRCONCE",
  "COMAH-176",
  "COMFM-52",
  "COMFM-54",
  "COMESTINOS",
  "COMFASUB",
  "COMSS-35",
  "COMSS-36",
  "COMSS-31",
  "COMSS-32",
  "COMSS-33",
  "COMSS-34",
  "COMART-322",
  "COMACA-111",
  "COMCM-26",
  "COMCM-22",
  "COMCM-21",
  "COMCM-23",
  "COMCM-24",
  "COMCM-25",
  "COMDT-144",
  "COMCF-11",
  "COMCF-12",
  "COMCF-13",
  "COMCF-14",
  "COMACP-119",
  "COMABH-302",
  "JECETEMI",
  "COMBASNAI",
  "COMESCLA",
  "JESERSIDI",
  "JESEHIN",
  "COMGROUNO",
  "EAN-33",
  "EAN-21",
  "COMBARVAL",
  "JESANA",
  "COMSERMANAV",
  "COMDESTELSA",
  "COMBAIM",
  "COMBIM-1",
  "COMBIM-2",
  "JESIM",
  "JEOES",
  "COMESTOES",
  "COMGRUSAL",
  "COMGOE-1",
  "COMGOE-2",
  "COMGOE-3",
  "JECEOES",
  "COMBACA",
  "DIHOBACA",
  "COMAH-175",
  "DIRSIMA",
  "JESERSIMAC",
  "JESIMACHI",
  "COMESGUICAFRAY",
  "JEPOLINAV",
  "COMDESPON-I",
  "COMARA-123",
  "COMACP-118",
  "COMESCRUZ",
  "COMESPITA",
  "COMBATUAN",
  "DINTEMAR(JESPERNOR)",
  "DISAMAR",
  "DIFOSMAR",
  "COMBACHI",
  "COMABH-306",
  "JECETEPITA",
  "JECETEMO",
  "JECETECAL",
  "COMZOUNO(JEPUCOPITA)",
  "DIRESUVAL",
  "DIRESNA",
  "JESCUSUB",
  "DIRENAMM",
  "JESGUESU",
  "DAP.(FO.CAS.MIL.PAL.GO)",
  "COMABH-303",
  "COMABH-304",
  "COMABH-305",
  "DIALI",
  "COMOPERAMA",
  "COMOPERPAC",
  "COMESNAPU",
  "COMESCUAMA",
  "COMSUBDRON",
  "COMESCUAEX",
  "COMESCUATA",
  "COMESCUATRA",
  "COMESCUAINS",
  "COMBAVETAC",
  "COMFLOTFLU",
  "COMBACOM",
  "COMBRIGANF",
  "COMBICBOLDT",
  "COMAHI-172",
  "COMESGUARD",
  "COMALY-313",
  "JESGUARCO",
  "JEOCIM",
  "COMOPERGUARD",
  "CAPIZORI",
  "CAPILARA",
  "CAPIPITA",
  "CAPIPIME",
  "CAPISALA",
  "CAPIBOTE",
  "CAPISUPE",
  "CAPIACHO",
  "CAPICALA",
  "CAPISCO",
  "CAPISUAN",
  "CAPIMOLE",
  "CAPILO",
  "CAPIMADO",
  "CAPIPUNO",
  "CAPIPUCA",
  "CAPIQUI",
  "CAPIYURI",
  "COMFM-55",
  "COMFM-56",
  "JESERNAVIMAR",
  "CAPICHAN",
  "DIRBIEMAR(SERVIC.FUNER)",
  "COSUATRES",
  "COMFM-57",
  "DICITEC",
  "CGT-150.2",
  "CGT-150.3",
  "CGT-150.4",
  "COMFM-58",
  "CGT-150.5",
  "COMPM-223",
  "CGT-150.6",
  "CGT-150.7",
  "CGT-150.8",
  "CGT-150.9",
  "COMCF-15",
  "COMFUINMAR",
  "COMFOE",
  "COMFUAVINAV",
  "COMESFAS",
  "DIREDUMAR",
  "JEDESMOLE",
  "DIRESGRUM(DIRECCION)",
  "DIRESGRUM(JESGRUM-IMA)",
  "COMGRUDOS",
  "COMESNAPI",
  "COMESGEMAR",
  "OFINAVCOCOFA",
  "COMBEV-161",
  "COMPM-204",
  "COMPM-205",
  "COMBSH-173",
  "COMPM-206",
  "COMPM-207",
  "COMRAS-180",
  "COMAMP-156",
  "COMBOP-171",
  "COMFM-53",
  "JEDICAP-5(UCF-289)",
  "COMCC-27",
  "COMBINGIMAR              ",
  "JESBUSAL",
  "COMCF-16",
  "JEDICAP-2",
  "UCF-RIO.INAMBARI",
  "UCF-RIO.PACAYA",
  "UCF-RIO.SAMIRA",
  "COMUCF-250",
  "DITRANAV",
  "DIRBINFRATER",
  "AGREDEF-ESPAÑA",
  "AGREDEFNAV-COREA",
  "AGREDEF-AUSTRALIA",
  "AGREDEF-AUSTRALIA(SINGAP",
  "OFINAVTRISUMIL",
  "OFINAVTRISUCEN",
  "DIRCOMAT",
  "DIRNOTEMAT",
  "COMARL-158",
  "JEARMANAV",
  "COMPO-201",
  "AGREDEFNAV_CANADA",
  "JESGUAFLU",
  "AGREDEFNAV-CHINA",
  "AGREDEFNAV-MEXICO",
  "COMPIAS-3101",
  "COMPIAS-3102",
  "COMPIAS-3103",
  "COMPIAS-3104",
  "EAN-23",
  "DIRCITEN(IESTPN-CITEN)",
  "COMBIMA-2",
  "COMBIMA-1",
  "COMBIM-3",
  "COMBATAR",
  "DIARNAVMAR",
  "COMPIAS-3120",
  "DIRESPROM",
  "DIPONAVSAB",
  "COMCIBERDEF",
  "COSUABARVAL",
  "COSUAGEMAR",
  "COSUCINCO",
  "COSUADOS",
  "COSUAPUN",
  "JECOSTEMO",
  "JESUEADMON",
  "JESUECAP",
  "JESUEOPERPAC",
  "JESUEBIE",
  "JESUEDU",
  "JESUESAL",
  "JESEALIMAZ",
  "JESUEMAB",
  "JEDESNAL",
  "COFA",
  "COMA",
  "COSUACUATRO",
  "CEU",
  "COSUABAIM",
  "COSUAUNO",
  "JESGRUM-5",
  "JESGRUM-1",
  "JESGRUM-3",
  "JESGRUM-4",
  "JAEH-174",
  "JECOSTECA",
  "JORMILICA",
  "JORMIURA",
  "JPC-220",
  "JPC-221",
  "JPC-219",
  "JPC-216",
  "JPC-218",
  "JPC-217",
  "JPC-215",
  "JPC-222",
  "JPC-224",
  "JPC-225",
  "JPC-226",
  "JPC-227",
  "JPC-228",
  "JPC-231",
  "JPC-236",
  "JPC-233",
  "JPC-232",
  "JPC-237",
  "JPC-235",
  "JPC-229",
  "JPC-230",
  "JPC-234",
  "JPC-238",
  "COMUCF-252",
  "COMUCF-251",
  "UCF-254",
  "JPF-256",
  "JPF-273",
  "JPF-260",
  "JPF-270",
  "JPF-266",
  "JPF-263",
  "JPF-264",
  "JPF-267",
  "JPF-271",
  "JPF-262",
  "JPF-261",
  "JPF-265",
  "JPF-272",
  "JPF-257",
  "JPF-274",
  "COMUCF-253",
  "JPL-292",
  "JPL-291",
  "JPL-290",
  "PL-293",
  "PL-294",
  "JPC-213",
  "JPC-214",
  "JEABP-340",
  "JEABP-341",
  "JEABP-337",
  "JEABP-338",
  "JEABP-339",
  "JEDESGUE",
  "JAEH-173",
  "JESUEOPERAMA",
  "JESUEHID",
  "JESUETEL",
  "TODACAPI",
  "TODACAFLU",
  "TODACALI",
  "TOTIRAMA",
  "TOTILICA",
  "TODUSERNAVIMAR",
  "TODUBAHIA",
  "TODUREX",
  "TODURINTE",
  "TOUGUARCO",
  "BUNAVEGA",
  "BUNAEXTE",
  "BUNALITO",
  "TODARAMA",
  "TODAR",
  "TOSUEOPERPAC",
  "TODACOMA",
  "TODARLICA",
  "TODELITO",
  "TODARTENA",
  "TOCOSUACUATRO",
  "TOCOSUAUNO",
  "TOCOSUACINCO",
  "TOCOSUATRES",
  "TOAGREDEF",
  "TOCETE",
  "TOCOSUABASNACA",
  "TOCOSUABARVAL",
  "TOCOSUAGEMAR",
  "TOCOSUABESAN",
  "TOCOSUABAIM",
  "TOCOSUAPUN",
  "TOCOFU",
  "TOCOMZONA",
  "TOCOSUADOS",
  "TODESMAR",
  "TOJEDICAP",
  "TOFIALM",
  "TOCOSUAPAC",
  "TODUSUB",
  "TODUESFAS",
  "TSUNAMI",
  "JESPERORPU",
  "COAM",
  "COSUABASNACA",
  "JESPERSUR",
  "JECOSTEPITA",
  "JECOSTIQUI",
  "COMBICLAYA",
  "JESPERNORI",
  "JESPERSOPU",
  "COLOMAR",
  "JORMIQUIPA",
  "JORMICHITE",
  "JORMACHO",
  "JORMILO",
  "JORMITOS",
  "JORMOLE",
  "JORMIPITA",
  "JORMIPIME",
  "JORMADO",
  "JORMIPUCA",
  "JORMISCO",
  "JORMIPUNO",
  "JORMISALA",
  "JORMISUAN",
  "JORMISUPE",
  "JORMILARA",
  "JORMIBES",
  "JORMIYURI",
  "JEDESTRE",
  "JEDESCHI",
  "JESUEPER",
  "COAGRUNAV",
  "CFT-150",
  "JEPONAVE",
  "JEPONAVAN",
  "JECEINOANF",
  "CFT-40",
  "JEODESPRO",
  "CGT-300.1",
  "CET-300.1.1.2",
  "CGT-150.1",
  "COMFAS-1",
  "COMCONAVRAEM",
  "DIGESPA",
  "COMALY-311",
  "JEOFIGESPA-01",
  "JEOFIGESPA-02",
  "JEOFIGESPA-03",
  "JEOFIGESPA-04",
  "JEOFIGESPA-05",
  "JEOFIGESPA-06",
  "JEOFIGESPA-07",
  "JEOFIGESPA-08",
  "JEOFIGESPA-09",
  "JEOFIGESPA-10",
  "CFT-22",
  "CGT-22.1",
  "CGT-22.2",
  "CGT-22.3",
  "CGT-22.4",
  "CGT-22.5",
  "CGT-22.6",
  "CGT-22.7",
  "CGT-22.8",
  "CGT-22.9",
  "TOFLOTFLU",
  "LIF-890",
  "LIF-902",
  "JPC-239",
  "COSUOPERAMA",
  "CUT-22.1.1",
  "CUT-22.1.2",
  "CUT-22.1.3",
  "CUT-22.1.4",
  "CUT-22.1.5",
  "CUT-22.1.6",
  "CUT-22.1.7",
  "CFT-24",
  "CFT-25",
  "COMCC-28",
  "DIRCAPEN",
  "TODOGENEMAR",
  "JECECOFA",
  "CFT-23",
  "JPC-249",
  "JPC-242",
  "JPC-240",
  "COMPIAS-3105",
  "COMPM-208",
  "COMPM-209",
  "DIREJEC",
  "OCI-MGP",
  "COMAUD",
  "CEREC",
  "SECOMAR",
  "SECOSUP",
  "SECOSUN",
  "PL-295",
  "PL-296",
  "COMGAOES",
  "CFT-21",
  "CGT-21.1",
  "CGT-21.2",
  "CGT-21.3",
  "CGT-21.4",
  "CGT-21.5",
  "CGT-21.6",
  "CGT-23.1",
  "CGT-23.2",
  "CGT-23.3",
  "CGT-23.4",
  "PRESUBCO",
  "DIPRESUMAR",
  "DICONMAR",
  "DITESOMAR",
  "JESHIDRO",
  "COSUOPERPAC",
  "COSUABESAN",
  "COSUAENZO",
  "COSUACINCO",
  "TOCOSUAENZO",
  "TOCOSUAMA",
  "CFT-12",
  "COSUACALA",
  "TOCOSUACALA",
  "CFT-32",
  "CFT-11",
  "CFT-13",
  "CFT-14",
  "CFT-15",
  "CFT-16",
  "CGT-17.1",
  "CFT-33",
  "CFT-34",
  "CFT-35",
  "CFT-36",
  "CGT-32.1",
  "CGT-32.2",
  "CGT-32.3",
  "CGT-32.4",
  "CGT-32.5",
  "CGT-32.6",
  "CGT-32.7",
  "CGT-32.8",
  "CGT-32.9",
  "CGT-32.10",
  "CFT-31",
  "CFT.37",
  'DINCYDET Direccion',
  'DINCYDET SubDireccion',
  'DINCYDET Departamento de Proyectos de Ingenieria',
  'DINCYDET Departamento de Control de Proyectos',
  'DINCYDET Departamento de Proyectos de Electronica',
  'DINCYDET Departamento de Sistemas operacionales',
  'DINCYDET Secretaria y Comunicaciones',
  'DINCYDET Estacion de radio',
  'DINCYDET Administracion',
];
