// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYen1_OpNkX03rXr2yQEtdiiLQdoWwhc',
    appId: '1:48491647126:web:7ad8edec43ff3d487432b7',
    messagingSenderId: '48491647126',
    projectId: 'gestion-dincydet',
    authDomain: 'gestion-dincydet.firebaseapp.com',
    storageBucket: 'gestion-dincydet.appspot.com',
    measurementId: 'G-TJ9RXMRGYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1J7DHt-YbNlyyRheudJPL5CNE763UvGU',
    appId: '1:48491647126:android:1963f71d93687a977432b7',
    messagingSenderId: '48491647126',
    projectId: 'gestion-dincydet',
    storageBucket: 'gestion-dincydet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7a8padzRlEMjDwa-RChUljETF2qqw9NA',
    appId: '1:48491647126:ios:7793c9dbcad7e18e7432b7',
    messagingSenderId: '48491647126',
    projectId: 'gestion-dincydet',
    storageBucket: 'gestion-dincydet.appspot.com',
    iosClientId: '48491647126-6uvcachi6qrnm3iv8gt8jn071243t0a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovilDincydet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7a8padzRlEMjDwa-RChUljETF2qqw9NA',
    appId: '1:48491647126:ios:7793c9dbcad7e18e7432b7',
    messagingSenderId: '48491647126',
    projectId: 'gestion-dincydet',
    storageBucket: 'gestion-dincydet.appspot.com',
    iosClientId: '48491647126-6uvcachi6qrnm3iv8gt8jn071243t0a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovilDincydet',
  );
}
